# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

Workout.create(user_id: 1, date: '01/02/2018')
Workout.create(user_id: 1, date: '02/02/2018')
Workout.create(user_id: 1, date: '03/02/2018')
Workout.create(user_id: 1, date: '05/02/2018')
Workout.create(user_id: 1, date: '07/02/2018')

Workout.create(user_id: 2, date: '02/02/2018')
Workout.create(user_id: 2, date: '04/02/2018')
Workout.create(user_id: 2, date: '06/02/2018')
Workout.create(user_id: 2, date: '08/02/2018')
Workout.create(user_id: 2, date: '10/02/2018')

Exercise.create(workout_id: 1, pattern: "Push", name: "Overhead Press", weight: "135", reps: 7, rpe: 8, daily_max: true)
Exercise.create(workout_id: 1, pattern: "Push", name: "Overhead Press", weight: "95", reps: 7, rpe: 4, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Pull", name: "Pull Up", weight: "25", reps: 8, rpe: 8, daily_max: false)
Exercise.create(workout_id: 2, pattern: "Pull", name: "Pull Up", weight: "25", reps: 7, rpe: 8, daily_max: false)
Exercise.create(workout_id: 3, pattern: "Squat", name: "Power Squat", weight: "295", reps: 8, rpe: 3, daily_max: false)
Exercise.create(workout_id: 3, pattern: "Squat", name: "Power Squat", weight: "315", reps: 9, rpe: 4, daily_max: true)
Exercise.create(workout_id: 4, pattern: "Hinge", name: "Deadlift", weight: "385", reps: 7, rpe: 8, daily_max: true)
Exercise.create(workout_id: 4, pattern: "Hinge", name: "Deadlift", weight: "365", reps: 5, rpe: 8, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Core", name: "Paloff Press", weight: "50", reps: 17, rpe: 3, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Core", name: "Paloff Press", weight: "50", reps: 15, rpe: 3, daily_max: false)

Exercise.create(workout_id: 5, pattern: "Push", name: "Bench Press", weight: "225", reps: 6, rpe: 3, daily_max: false)
Exercise.create(workout_id: 7, pattern: "Push", name: "Bench Press", weight: "245", reps: 5, rpe: 8, daily_max: true)
Exercise.create(workout_id: 8, pattern: "Pull", name: "Barbell Row", weight: "275", reps: 6, rpe: 3, daily_max: true)
Exercise.create(workout_id: 9, pattern: "Pull", name: "Barbell Row", weight: "185", reps: 4, rpe: 4, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Squat", name: "Olympic Squat", weight: "275", reps: 6, rpe: 3, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Squat", name: "Olympic Squat", weight: "305", reps: 9, rpe: 4, daily_max: true)
Exercise.create(workout_id: 7, pattern: "Hinge", name: "Power Clean", weight: "205", reps: 6, rpe: 8, daily_max: false)
Exercise.create(workout_id: 8, pattern: "Hinge", name: "Power Clean", weight: "245", reps: 4, rpe: 4, daily_max: true)
Exercise.create(workout_id: 9, pattern: "Core", name: "Situp", weight: "50", reps: 15, rpe: 8, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Core", name: "Situp", weight: "50", reps: 15, rpe: 3, daily_max: false)

Exercise.create(workout_id: 1, pattern: "Push", name: "Overhead Press", weight: "135", reps: 6, rpe: 3, daily_max: false)
Exercise.create(workout_id: 1, pattern: "Push", name: "Overhead Press", weight: "185", reps: 2, rpe: 8, daily_max: true)
Exercise.create(workout_id: 5, pattern: "Pull", name: "Pull Up", weight: "25", reps: 8, rpe: 3, daily_max: false)
Exercise.create(workout_id: 2, pattern: "Pull", name: "Pull Up", weight: "25", reps: 4, rpe: 8, daily_max: false)
Exercise.create(workout_id: 6, pattern: "Squat", name: "Power Squat", weight: "315", reps: 8, rpe: 3, daily_max: true)
Exercise.create(workout_id: 3, pattern: "Squat", name: "Power Squat", weight: "315", reps: 6, rpe: 8, daily_max: false)
Exercise.create(workout_id: 4, pattern: "Hinge", name: "Deadlift", weight: "345", reps: 56, rpe: 3, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Hinge", name: "Deadlift", weight: "365", reps: 4, rpe: 4, daily_max: true)
Exercise.create(workout_id: 5, pattern: "Core", name: "Paloff Press", weight: "50", reps: 16, rpe: 8, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Core", name: "Paloff Press", weight: "50", reps: 15, rpe: 3, daily_max: false)

Exercise.create(workout_id: 6, pattern: "Push", name: "Bench Press", weight: "225", reps: 3, rpe: 3, daily_max: true)
Exercise.create(workout_id: 7, pattern: "Push", name: "Bench Press", weight: "205", reps: 5, rpe: 8, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Pull", name: "Barbell Row", weight: "155", reps: 8, rpe: 8, daily_max: false)
Exercise.create(workout_id: 9, pattern: "Pull", name: "Barbell Row", weight: "185", reps: 4, rpe: 4, daily_max: true)
Exercise.create(workout_id: 10, pattern: "Squat", name: "Olympic Squat", weight: "275", reps: 8, rpe: 8, daily_max: true)
Exercise.create(workout_id: 6, pattern: "Squat", name: "Olympic Squat", weight: "255", reps: 9, rpe: 4, daily_max: false)
Exercise.create(workout_id: 7, pattern: "Hinge", name: "Power Clean", weight: "205", reps: 5, rpe: 7, daily_max: true)
Exercise.create(workout_id: 8, pattern: "Hinge", name: "Power Clean", weight: "205", reps: 8, rpe: 4, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Core", name: "Situp", weight: "50", reps: 15, rpe: 8, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Core", name: "Situp", weight: "50", reps: 15, rpe: 8, daily_max: false)

Exercise.create(workout_id: 6, pattern: "Push", name: "Overhead Press", weight: "135", reps: 8, rpe: 9, daily_max: true)
Exercise.create(workout_id: 8, pattern: "Push", name: "Overhead Press", weight: "135", reps: 5, rpe: 7, daily_max: false)
Exercise.create(workout_id: 2, pattern: "Pull", name: "Pull Up", weight: "25", reps: 8, rpe: 8, daily_max: false)
Exercise.create(workout_id: 8, pattern: "Pull", name: "Pull Up", weight: "25", reps: 4, rpe: 8, daily_max: false)
Exercise.create(workout_id: 9, pattern: "Squat", name: "Power Squat", weight: "365", reps: 8, rpe: 9, daily_max: true)
Exercise.create(workout_id: 3, pattern: "Squat", name: "Power Squat", weight: "315", reps: 9, rpe: 9, daily_max: false)
Exercise.create(workout_id: 4, pattern: "Hinge", name: "Deadlift", weight: "405", reps: 5, rpe: 10, daily_max: true)
Exercise.create(workout_id: 4, pattern: "Hinge", name: "Deadlift", weight: "365", reps: 4, rpe: 8, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Core", name: "Paloff Press", weight: "50", reps: 15, rpe: 8, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Core", name: "Paloff Press", weight: "50", reps: 15, rpe: 8, daily_max: false)

Exercise.create(workout_id: 6, pattern: "Push", name: "Bench Press", weight: "225", reps: 8, rpe: 8, daily_max: false)
Exercise.create(workout_id: 5, pattern: "Push", name: "Bench Press", weight: "255", reps: 5, rpe: 8, daily_max: true)
Exercise.create(workout_id: 8, pattern: "Pull", name: "Barbell Row", weight: "205", reps: 8, rpe: 8, daily_max: true)
Exercise.create(workout_id: 9, pattern: "Pull", name: "Barbell Row", weight: "185", reps: 4, rpe: 8, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Squat", name: "Olympic Squat", weight: "295", reps: 8, rpe: 7, daily_max: true)
Exercise.create(workout_id: 6, pattern: "Squat", name: "Olympic Squat", weight: "275", reps: 6, rpe: 8, daily_max: false)
Exercise.create(workout_id: 7, pattern: "Hinge", name: "Power Clean", weight: "185", reps: 5, rpe: 8, daily_max: false)
Exercise.create(workout_id: 8, pattern: "Hinge", name: "Power Clean", weight: "205", reps: 4, rpe: 7, daily_max: true)
Exercise.create(workout_id: 9, pattern: "Core", name: "Situp", weight: "100", reps: 15, rpe: 8, daily_max: false)
Exercise.create(workout_id: 10, pattern: "Core", name: "Situp", weight: "50", reps: 13, rpe: 8, daily_max: false)
